// This file is auto-generated by @hey-api/openapi-ts

export const CreateLayoutRequestSchema = {
    type: 'object',
    properties: {
        userId: {
            type: 'string',
            format: 'uuid'
        },
        restaurantId: {
            type: 'string',
            format: 'uuid'
        },
        layoutJson: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const CreateRestaurantRequestSchema = {
    type: 'object',
    properties: {
        createdById: {
            type: 'string',
            format: 'uuid'
        },
        restaurantName: {
            type: 'string',
            nullable: true
        },
        restaurantCode: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const CreateTableRequestSchema = {
    type: 'object',
    properties: {
        identification: {
            type: 'string',
            nullable: true
        },
        capacity: {
            type: 'integer',
            format: 'int32'
        },
        layoutId: {
            type: 'string',
            format: 'uuid'
        }
    },
    additionalProperties: false
} as const;

export const EditLayoutRequestSchema = {
    type: 'object',
    properties: {
        userId: {
            type: 'string',
            format: 'uuid'
        },
        restaurantId: {
            type: 'string',
            format: 'uuid'
        },
        layoutJson: {
            type: 'string',
            nullable: true
        },
        layoutItems: {
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const ForgotPasswordSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const LayoutChairSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        type: {
            type: 'string',
            nullable: true
        },
        color: {
            type: 'string',
            nullable: true
        },
        x: {
            type: 'integer',
            format: 'int32'
        },
        y: {
            type: 'integer',
            format: 'int32'
        },
        rotation: {
            type: 'integer',
            format: 'int32'
        }
    },
    additionalProperties: false
} as const;

export const LoggedUserSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        isAdmin: {
            type: 'boolean'
        },
        name: {
            type: 'string',
            nullable: true
        },
        isAuthenticated: {
            type: 'boolean'
        }
    },
    additionalProperties: false
} as const;

export const LoginSchema = {
    required: [
        'email',
        'password'
    ],
    type: 'object',
    properties: {
        email: {
            minLength: 1,
            type: 'string',
            format: 'email'
        },
        password: {
            minLength: 1,
            type: 'string'
        }
    },
    additionalProperties: false
} as const;

export const RegisterSchema = {
    required: [
        'email',
        'password'
    ],
    type: 'object',
    properties: {
        email: {
            minLength: 1,
            type: 'string',
            format: 'email'
        },
        password: {
            minLength: 1,
            type: 'string'
        }
    },
    additionalProperties: false
} as const;

export const ReservationSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        userId: {
            type: 'string',
            format: 'uuid'
        },
        tableId: {
            type: 'string',
            format: 'uuid'
        },
        numberOfGuests: {
            type: 'integer',
            format: 'int32'
        },
        slots: {
            type: 'integer',
            format: 'int32'
        },
        reservedByFirstName: {
            type: 'string',
            nullable: true
        },
        reservedByLastName: {
            type: 'string',
            nullable: true
        },
        reservedByEmail: {
            type: 'string',
            nullable: true
        },
        dateOfReservation: {
            type: 'string',
            format: 'date-time'
        }
    },
    additionalProperties: false
} as const;

export const ReserveGuestRequestSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        tableId: {
            type: 'string',
            format: 'uuid'
        },
        numberOfGuests: {
            type: 'integer',
            format: 'int32'
        },
        slots: {
            type: 'integer',
            format: 'int32'
        },
        firstName: {
            type: 'string',
            nullable: true
        },
        lastName: {
            type: 'string',
            nullable: true
        },
        email: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const ReserveRequestSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        tableId: {
            type: 'string',
            format: 'uuid'
        },
        numberOfGuests: {
            type: 'integer',
            format: 'int32'
        },
        slots: {
            type: 'integer',
            format: 'int32'
        },
        dateOfReservation: {
            type: 'string',
            format: 'date-time'
        }
    },
    additionalProperties: false
} as const;

export const ResetPasswordRequestModelSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string',
            nullable: true
        },
        token: {
            type: 'string',
            nullable: true
        },
        newPassword: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const RestaurantSchema = {
    required: [
        'createdAt',
        'createdById',
        'restaurantCode',
        'restaurantName'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        restaurantUsers: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/RestaurantUser'
            },
            nullable: true
        },
        createdById: {
            type: 'string',
            format: 'uuid'
        },
        createdBy: {
            $ref: '#/components/schemas/User'
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        },
        restaurantName: {
            maxLength: 100,
            minLength: 1,
            type: 'string'
        },
        restaurantCode: {
            maxLength: 10,
            minLength: 1,
            type: 'string'
        },
        reservationsDuration: {
            type: 'integer',
            format: 'int32'
        },
        openingHour: {
            type: 'integer',
            format: 'int32'
        },
        openingMinute: {
            type: 'integer',
            format: 'int32'
        },
        closingHour: {
            type: 'integer',
            format: 'int32'
        },
        closingMinute: {
            type: 'integer',
            format: 'int32'
        },
        description: {
            maxLength: 500,
            type: 'string',
            nullable: true
        },
        tags: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/Tag'
            },
            nullable: true
        },
        published: {
            type: 'boolean'
        }
    },
    additionalProperties: false
} as const;

export const RestaurantRoleSchema = {
    enum: [
        1,
        2,
        3
    ],
    type: 'integer',
    format: 'int32'
} as const;

export const RestaurantUserSchema = {
    type: 'object',
    properties: {
        userId: {
            type: 'string',
            format: 'uuid'
        },
        user: {
            $ref: '#/components/schemas/User'
        },
        restaurantId: {
            type: 'string',
            format: 'uuid'
        },
        restaurant: {
            $ref: '#/components/schemas/Restaurant'
        },
        role: {
            $ref: '#/components/schemas/RestaurantRole'
        }
    },
    additionalProperties: false
} as const;

export const TableSchema = {
    required: [
        'identification'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        layoutId: {
            type: 'string',
            format: 'uuid'
        },
        identification: {
            maxLength: 100,
            minLength: 1,
            type: 'string'
        },
        capacity: {
            maximum: 99,
            minimum: 1,
            type: 'integer',
            format: 'int32'
        },
        reservations: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/Reservation'
            },
            nullable: true
        },
        type: {
            type: 'string',
            nullable: true
        },
        color: {
            type: 'string',
            nullable: true
        },
        x: {
            type: 'integer',
            format: 'int32'
        },
        y: {
            type: 'integer',
            format: 'int32'
        },
        rotation: {
            type: 'integer',
            format: 'int32'
        },
        width: {
            type: 'integer',
            format: 'int32'
        },
        height: {
            type: 'integer',
            format: 'int32'
        },
        chairs: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/LayoutChair'
            },
            nullable: true
        },
        info: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const TagSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            format: 'int64'
        },
        tagName: {
            maxLength: 30,
            minLength: 3,
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const TokenSchema = {
    required: [
        'email',
        'sessionToken'
    ],
    type: 'object',
    properties: {
        email: {
            minLength: 1,
            type: 'string',
            format: 'email'
        },
        sessionToken: {
            minLength: 1,
            type: 'string'
        }
    },
    additionalProperties: false
} as const;

export const UpdateRestaurantRequestSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        restaurantName: {
            type: 'string',
            nullable: true
        },
        restaurantCode: {
            type: 'string',
            nullable: true
        },
        reservationsDuration: {
            type: 'integer',
            format: 'int32'
        },
        openingHour: {
            type: 'integer',
            format: 'int32'
        },
        openingMinute: {
            type: 'integer',
            format: 'int32'
        },
        closingHour: {
            type: 'integer',
            format: 'int32'
        },
        closingMinute: {
            type: 'integer',
            format: 'int32'
        },
        description: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const UserSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        userName: {
            type: 'string',
            nullable: true
        },
        normalizedUserName: {
            type: 'string',
            nullable: true
        },
        email: {
            type: 'string',
            nullable: true
        },
        normalizedEmail: {
            type: 'string',
            nullable: true
        },
        emailConfirmed: {
            type: 'boolean'
        },
        passwordHash: {
            type: 'string',
            nullable: true
        },
        securityStamp: {
            type: 'string',
            nullable: true
        },
        concurrencyStamp: {
            type: 'string',
            nullable: true
        },
        phoneNumber: {
            type: 'string',
            nullable: true
        },
        phoneNumberConfirmed: {
            type: 'boolean'
        },
        twoFactorEnabled: {
            type: 'boolean'
        },
        lockoutEnd: {
            type: 'string',
            format: 'date-time',
            nullable: true
        },
        lockoutEnabled: {
            type: 'boolean'
        },
        accessFailedCount: {
            type: 'integer',
            format: 'int32'
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        },
        modifiedAt: {
            type: 'string',
            format: 'date-time',
            nullable: true
        },
        deletedAt: {
            type: 'string',
            format: 'date-time',
            nullable: true
        },
        restaurantUsers: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/RestaurantUser'
            },
            nullable: true
        },
        googleId: {
            type: 'string',
            nullable: true
        },
        provider: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;
