// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5000' | (string & {});
};

export type CreateLayoutRequest = {
    userId?: string;
    restaurantId?: string;
    layoutJson?: string | null;
};

export type CreateRestaurantRequest = {
    createdById?: string;
    restaurantName?: string | null;
    restaurantCode?: string | null;
};

export type CreateTableRequest = {
    identification?: string | null;
    capacity?: number;
    layoutId?: string;
};

export type EditLayoutRequest = {
    userId?: string;
    restaurantId?: string;
    layoutJson?: string | null;
    layoutItems?: unknown;
};

export type ForgotPassword = {
    email?: string | null;
};

export type LayoutChair = {
    id?: string;
    type?: string | null;
    color?: string | null;
    x?: number;
    y?: number;
    rotation?: number;
};

export type LoggedUser = {
    id?: string;
    isAdmin?: boolean;
    name?: string | null;
    isAuthenticated?: boolean;
};

export type Login = {
    email: string;
    password: string;
};

export type Register = {
    email: string;
    password: string;
};

export type Reservation = {
    id?: string;
    userId?: string;
    tableId?: string;
    numberOfGuests?: number;
    slots?: number;
    reservedByFirstName?: string | null;
    reservedByLastName?: string | null;
    reservedByEmail?: string | null;
    dateOfReservation?: string;
};

export type ReserveGuestRequest = {
    id?: string;
    tableId?: string;
    numberOfGuests?: number;
    slots?: number;
    firstName?: string | null;
    lastName?: string | null;
    email?: string | null;
};

export type ReserveRequest = {
    id?: string;
    tableId?: string;
    numberOfGuests?: number;
    slots?: number;
    dateOfReservation?: string;
};

export type ResetPasswordRequestModel = {
    email?: string | null;
    token?: string | null;
    newPassword?: string | null;
};

export type Restaurant = {
    id?: string;
    restaurantUsers?: Array<RestaurantUser> | null;
    createdById: string;
    createdBy?: User;
    createdAt: string;
    restaurantName: string;
    restaurantCode: string;
    reservationsDuration?: number;
    openingHour?: number;
    openingMinute?: number;
    closingHour?: number;
    closingMinute?: number;
    description?: string | null;
    tags?: Array<Tag> | null;
    published?: boolean;
};

export type RestaurantRole = 1 | 2 | 3;

export type RestaurantUser = {
    userId?: string;
    user?: User;
    restaurantId?: string;
    restaurant?: Restaurant;
    role?: RestaurantRole;
};

export type Table = {
    id?: string;
    layoutId?: string;
    identification: string;
    capacity?: number;
    reservations?: Array<Reservation> | null;
    type?: string | null;
    color?: string | null;
    x?: number;
    y?: number;
    rotation?: number;
    width?: number;
    height?: number;
    chairs?: Array<LayoutChair> | null;
    info?: string | null;
};

export type Tag = {
    id?: number;
    tagName?: string | null;
};

export type Token = {
    email: string;
    sessionToken: string;
};

export type UpdateRestaurantRequest = {
    id?: string;
    restaurantName?: string | null;
    restaurantCode?: string | null;
    reservationsDuration?: number;
    openingHour?: number;
    openingMinute?: number;
    closingHour?: number;
    closingMinute?: number;
    description?: string | null;
};

export type User = {
    id?: string;
    userName?: string | null;
    normalizedUserName?: string | null;
    email?: string | null;
    normalizedEmail?: string | null;
    emailConfirmed?: boolean;
    passwordHash?: string | null;
    securityStamp?: string | null;
    concurrencyStamp?: string | null;
    phoneNumber?: string | null;
    phoneNumberConfirmed?: boolean;
    twoFactorEnabled?: boolean;
    lockoutEnd?: string | null;
    lockoutEnabled?: boolean;
    accessFailedCount?: number;
    createdAt?: string;
    modifiedAt?: string | null;
    deletedAt?: string | null;
    restaurantUsers?: Array<RestaurantUser> | null;
    googleId?: string | null;
    provider?: string | null;
};

export type PostRegisterData = {
    body?: Register;
    path?: never;
    query?: never;
    url: '/register';
};

export type PostRegisterErrors = {
    /**
     * Bad Request
     */
    400: unknown;
};

export type PostRegisterResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostLoginData = {
    body?: Login;
    path?: never;
    query?: never;
    url: '/login';
};

export type PostLoginResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostVerifyEmailData = {
    body?: Token;
    path?: never;
    query?: never;
    url: '/verify-email';
};

export type PostVerifyEmailResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUserInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user-info';
};

export type GetUserInfoResponses = {
    /**
     * OK
     */
    200: LoggedUser;
};

export type GetUserInfoResponse = GetUserInfoResponses[keyof GetUserInfoResponses];

export type PostRefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/refresh';
};

export type PostRefreshResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/logout';
};

export type PostLogoutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetTestMeBeforeLoginAndAfterData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/testMeBeforeLoginAndAfter';
};

export type GetTestMeBeforeLoginAndAfterResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostForgotPasswordData = {
    body?: ForgotPassword;
    path?: never;
    query?: never;
    url: '/forgot-password';
};

export type PostForgotPasswordResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostResetPasswordData = {
    body?: ResetPasswordRequestModel;
    path?: never;
    query?: never;
    url: '/reset-password';
};

export type PostResetPasswordResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetTestmailData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/testmail';
};

export type GetTestmailResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetLByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/l/{id}';
};

export type GetLByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetLayoutByRestaurantIdData = {
    body?: never;
    path: {
        restaurantId: string;
    };
    query?: never;
    url: '/layout/{restaurantId}';
};

export type GetLayoutByRestaurantIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostCreateLayoutData = {
    body?: CreateLayoutRequest;
    path?: never;
    query?: never;
    url: '/create-layout';
};

export type PostCreateLayoutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostEditLayoutData = {
    body?: EditLayoutRequest;
    path?: never;
    query?: {
        id?: string;
    };
    url: '/edit-layout';
};

export type PostEditLayoutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetMyRestaurantsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/my-restaurants';
};

export type GetMyRestaurantsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetTimeslotsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/timeslots';
};

export type GetTimeslotsResponses = {
    /**
     * OK
     */
    200: Array<Reservation>;
};

export type GetTimeslotsResponse = GetTimeslotsResponses[keyof GetTimeslotsResponses];

export type GetTimeslotstableData = {
    body?: never;
    path?: never;
    query?: {
        tableId?: string;
    };
    url: '/timeslotstable';
};

export type GetTimeslotstableResponses = {
    /**
     * OK
     */
    200: Array<Reservation>;
};

export type GetTimeslotstableResponse = GetTimeslotstableResponses[keyof GetTimeslotstableResponses];

export type PostReserveData = {
    body?: ReserveRequest;
    path?: never;
    query?: never;
    url: '/reserve';
};

export type PostReserveErrors = {
    /**
     * Bad Request
     */
    400: unknown;
};

export type PostReserveResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostReserveGuestData = {
    body?: ReserveGuestRequest;
    path?: never;
    query?: never;
    url: '/reserve-guest';
};

export type PostReserveGuestErrors = {
    /**
     * Bad Request
     */
    400: unknown;
};

export type PostReserveGuestResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUrData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ur';
};

export type GetUrResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostCreateRestaurantData = {
    body?: CreateRestaurantRequest;
    path?: never;
    query?: never;
    url: '/create-restaurant';
};

export type PostCreateRestaurantResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutUpdateRestaurantData = {
    body?: UpdateRestaurantRequest;
    path?: never;
    query?: {
        id?: string;
    };
    url: '/update-restaurant';
};

export type PutUpdateRestaurantResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetRByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/r/{id}';
};

export type GetRByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetRestaurantsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/restaurants';
};

export type GetRestaurantsResponses = {
    /**
     * OK
     */
    200: Array<Restaurant>;
};

export type GetRestaurantsResponse = GetRestaurantsResponses[keyof GetRestaurantsResponses];

export type GetCheckRestaurantCodeData = {
    body?: never;
    path?: never;
    query?: {
        code?: string;
    };
    url: '/check-restaurant-code';
};

export type GetCheckRestaurantCodeResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostCreateTableData = {
    body?: CreateTableRequest;
    path?: never;
    query?: never;
    url: '/create-table';
};

export type PostCreateTableResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetTByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/t/{id}';
};

export type GetTByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetTablesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tables';
};

export type GetTablesResponses = {
    /**
     * OK
     */
    200: Array<Table>;
};

export type GetTablesResponse = GetTablesResponses[keyof GetTablesResponses];

export type GetWeatherData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/weather';
};

export type GetWeatherResponses = {
    /**
     * OK
     */
    200: unknown;
};
